version: "3.7"
services:

  news_app:
    build: './news_app_project'
    restart: always
    volumes:
      - ./news_app_project/news_app/:/home/djangoApp
    ports:
      - 8001:8001

  flask_app:
    build: './flask_app'
    restart: always
    volumes:
      - ./flask_app/:/home/flaskApp
    ports:
      - 8000:8000

    depends_on:
      - redis

  
  simple_worker:
    build: './simple_worker'
    restart: always
    depends_on:
      - redis
      - flask_app

  redis:
    image: 'redis:4-alpine'
    restart: always
    ports:
      - 6379:6379

  nginx:
    build: './nginx'
    restart: always
    ports:
      - 80:80
    volumes:
      - ./static/:/home/app/staticfiels
