# Generated by Django 4.2.6 on 2023-10-23 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_preview_news', models.ImageField(upload_to='photo_preview_news/', verbose_name='Изображение заставки новости')),
                ('title', models.CharField(max_length=256, verbose_name='Название новости')),
                ('shortDescription', models.TextField(verbose_name='Краткое описание новости')),
                ('datePublished', models.DateField(default=datetime.date.today, verbose_name='дата публикации новости')),
                ('textNews', models.TextField(verbose_name='Содержимое новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
