FROM python:3.10-slim-bullseye


RUN mkdir -p /home/djangoApp
WORKDIR /home/djangoApp

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["gunicorn","-b", "0.0.0.0:8001", "admin_panel.wsgi:application"]

EXPOSE 8001